config/routes.rb
Rails.application.routes.draw do

  scope module: :public do

    root :to => "homes#top"
    get 'about' => 'homes#about'

    resource :customers, only: [:edit, :update] do
      get 'my_page' => 'customers#show'
      get 'unsubscribe' => 'customers#unsubscribe'
      patch 'withdraw' => 'customers#withdraw'
    end

    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :items, only: [:index, :show] do
      get 'search' => "items#search"
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      post 'confirm' => 'orders#confirm'
      collection do
        get 'complete'
      end
    end

  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root :to => "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end

  def total_item_price
    total_item_price = 0
    self.each do |cart_item|
      sum = cart_item.subtotal
      total_item_price += sum
    end
    return total_item_price
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items

    has_many :cart_items, dependent: :destroy
    has_many :items, through: :cart_items
    has_many :addresses, dependent: :destroy
    has_many :orders, dependent: :destroy

 def full_name
  self.last_name + self.first_name
 end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  belongs_to :genre
  
  has_many :cart_items, dependent: :destroy
  has_many :customers, through: :cart_items

  has_one_attached :image_id
  
  validates :name, presence: true
  validates :image_id, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_image_id
    (image_id.attached?) ? image_id : 'no_image.jpg'
  end

  ## 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirm: 1, making: 2, preparing: 3, shipped: 4}

  def total_product_price
    total_product_price = 0
    self.order_details.each do |order_detail|
      sum = order_detail.price * order_detail.amount
      total_product_price += sum
    end
    return total_product_price
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { impossible: 0, waiting: 1, making: 2, finished: 3 }
  
  def total_item_price
    price*amount
  end
  
  
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path

  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page])

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.page(params[:page])
      render 'index'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.page(params[:page])
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image_id, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @order_details = @order.order_details.all

  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status_before_type_cast == 1
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/genres/_form.html.erb
<% if genre.name == nil %>
  <%= form_with model: genre, url: '/admin/genres', method: :post, local: true do |f|  %>
  <div class="form-group row ml-3">
    <div class="col-2 ml-5 font-weight-bold">
     <%= f.label "ジャンル名" %>
    </div>
    <div class="col-2 mr-3">
     <%= f.text_field :name, placeholder: "ジャンル名" %>
    </div>
    <div class="col-2 ml-5">
     <%= f.submit "新規登録", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
<% else %>
  <%= form_with model: genre, url: admin_genre_path(genre), method: :patch, local: true do |f|  %>
   <div class="form-group row font-weight-bold">
     <%= f.label "ジャンル名" %>
     <div class="col-2 ml-5 mr-3">
      <%= f.text_field :name %>
     </div>
     <div class="col-2 ml-5">
      <%= f.submit "変更を保存", class: "btn btn-success" %>
     </div>
    </div>
  <% end %>
<% end %>

app/views/admin/genres/edit.html.erb
<div class="container-fluid">
  <div class="row offset-1 mt-3 mb-5">
    <h5><mark class="bg-light">ジャンル編集</mark></h5>
  </div>
  <div class="offset-1">
   <%= render 'form', genre: @genre %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container-fluid">
  <div class="row offset-1 mt-3 mb-5">
    <h5><mark class="bg-light">ジャンル一覧・追加</mark></h5>
  </div>

   <%= render 'form', genre: @genre %>

  <div class="col-lg-4 mt-5 ml-5">
    <table class="table">
      <thead class="table-secondary">
        <tr>
          <th class="text-center">ジャンル</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td class="text-center align-middle"><%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-success" %></td>
        </tr>
         <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/_item.html.erb
      <div class="form-group row justify-content-center">
        <%= f.label :商品画像, class: "col-md-2 control-label" %>
        <div class="col-6">
         <%= f.file_field :image_id, accept: "image/*" %>
        </div>
      </div>
      <div class="form-group row justify-content-center">
        <%= f.label :商品名, class: "col-md-2 control-label" %>
        <div class="col-6">
          <%= f.text_field :name, placeholder: "商品名", class: "form-control" %>
        </div>
      </div>
      <div class="form-group row justify-content-center">
        <%= f.label :商品説明, class: "col-md-2 control-label" %>
        <div class="col-6">
          <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: "form-control"%>
        </div>
      </div>
      <div class="form-group row justify-content-center">
        <%= f.label :ジャンル, class: "col-md-2 control-label" %>
        <div class="col-6">
          <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "----", class: "form-control" %>
        </div>
      </div>
      <div class="form-group row justify-content-center">
        <%= f.label :税抜価格, class: "col-md-2 control-label" %>
        <div class="col-6">
          <%= f.text_field :price, placeholder: "1000", class: "form-control"%>
        </div>
        <span>円</span>
      </div>
      <div class="form-group row justify-content-center">
        <%= f.label :販売ステータス, class: "col-md-3 control-label" %>
        <div class="col-5">
         <%= f.radio_button :is_active, 'true' %>
         <%= f.label :is_active, '販売中', value: true %>
         <%= f.radio_button :is_active, 'false' %>
         <%= f.label :is_active, '販売停止中', value: false %>
        </div>
      </div>

app/views/admin/items/edit.html.erb
<div class="container">
  <h3>商品編集</h3>
  <div class="row justify-content-center">
    <div class="col-8">
      <%= form_with(model: [ :admin, @item ]) do |f| %>
       <%= render 'item', f: f %>
      <div class="form-group row justify-content-center">
        <%= f.submit "変更を保存", class: 'btn btn-success' %>
      </div>
    　<% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="col-3">
      <h3><mark class="bg-light">商品一覧</mark></h3>
    </div>
    <div class="col-1 offset-8 p-2">
      <%= link_to new_admin_item_path do %>
       <button type="button" class="btn btn-bg-white btn--shadow btn--circle rounded-circle p-0" style="width:3rem;height:3rem;">＋</button>
       <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-10 offset-1">
    <table class="table">
      <thead>
        <tr class="table-secondary">
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active == true %>
             <p>販売中</p>
            <% else %>
             <p>販売停止中</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h3><mark class="bg-light">商品新規登録</mark></h3>
  <div class="row justify-content-center">
    <div class="col-8">
      <%= form_with(model: [ :admin, @item ]) do |f| %>
       <%= render 'item', f: f %>
      <div class="form-group row justify-content-center">
        <%= f.submit "新規登録", class: 'btn btn-success' %>
      </div>
    　<% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h3>商品詳細</h3>
  <div class="row">
    <div class="col-lg-4">
      <%= image_tag @item.get_image_id, size: "200x200" %>
    </div>

    <div class="col-lg-8">
      <table class="table table-borderless">
        <tbody>
           <tr>
             <td>商品名</td>
             <td><%= @item.name %></td>
           </tr>
           <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td>税込価格(税抜価格)</td>
            <td>
             <%= @item.with_tax_price.to_s(:delimited)%>
             (<%= @item.price.to_s(:delimited) %>)円
            </td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td>
              <% if @item.is_active == true %>
               <p class="text-success">販売中</p>
              <% else %>
               <p class="text-danger">販売停止中</p>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-4 offset-5">
    <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
  </div>
</div>

app/views/admin/orders/show.html.erb
  <div class="container">
    <div class="col-12">
      <h3>注文履歴詳細</h3>

      <table class="table table-borderless">
        <tbody>
          <tr>
            <th class="w-25">購入者</th>
            <td>
              <%= link_to admin_customer_path(@customer) do %>
                <%= @customer.full_name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th>注文日</th>
            <td>
              <%= @order.created_at.strftime('%Y/%m/%d') %>
            </td>
          </tr>
          <tr>
            <th>配送先</th>
            <td>
              〒<%= @order.postal_code.to_s.insert(3, "-") + " " + @order.address %><br>
              <%= @order.name %>
            </td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <th>注文ステータス</th>

            <td class="align-content-center">
              <%= form_with model: [:admin, @order], method: :patch, local: true do |f| %>
              <%= f.select :status, options_for_select(Order.statuses_i18n.invert, selected: @order.status), class: "form-control" %>
              <%= f.submit "更新", class:"btn btn-sm btn-success ml-3" %>
              <% end %>
            </td>

          </tr>
        </tbody>
    </table>

    <div class="d-flex align-items-end">
      <div>
      <table class="table">
        <thead>
          <tr class="table-secondary">
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td class="text-center"><%= order_detail.item.name %></td>
            <td class="text-center"><%= order_detail.price.to_s(:delimited) %></td>
            <td class="text-center"><%= order_detail.amount %></td>
            <td class="text-center"><%= (order_detail.price * order_detail.amount).to_s(:delimited) %></td>

            <td>
              <%= form_with model:  [:admin, order_detail], method: :patch, local: true do  |f| %>
                <%= f.select :making_status, options_for_select(OrderDetail.making_statuses_i18n.invert, selected: order_detail.making_status) %>
                <%= f.submit "更新", class:"btn btn-sm btn-success ml-3" %>
              <% end %>
            </td>

          </tr>
          <% end %>
        </tbody>
      </table>
      </div>

      <div class="ml-5">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th>商品合計</th>
              <td class="float-right"><%= @order.total_product_price.to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <th>送料</th>
              <td class="float-right"><%= @order.shipping_cost %>円</td>
            </tr>
            <tr>
              <th>請求額合計</th>
              <th class="float-right"><%= @order.total_payment.to_s(:delimited) %>円</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>