config/routes.rb
Rails.application.routes.draw do

  scope module: :public do

    root :to => "homes#top"
    get 'about' => 'homes#about'

    resource :customers, only: [:edit, :update] do
      get 'my_page' => 'customers#show'
      get 'unsubscribe' => 'customers#unsubscribe'
      patch 'withdraw' => 'customers#withdraw'
    end

    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :items, only: [:index, :show] do
      get 'search' => "items#search"
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      post 'confirm' => 'orders#confirm'
      collection do
        get 'complete'
      end
    end

  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    root :to => "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def subtotal
    item.with_tax_price * amount
  end

  def total_item_price
    total_item_price = 0
    self.each do |cart_item|
      sum = cart_item.subtotal
      total_item_price += sum
    end
    return total_item_price
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items

    has_many :cart_items, dependent: :destroy
    has_many :items, through: :cart_items
    has_many :addresses, dependent: :destroy
    has_many :orders, dependent: :destroy

 def full_name
  self.last_name + self.first_name
 end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  belongs_to :genre
  
  has_many :cart_items, dependent: :destroy
  has_many :customers, through: :cart_items

  has_one_attached :image_id
  
  validates :name, presence: true
  validates :image_id, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_image_id
    (image_id.attached?) ? image_id : 'no_image.jpg'
  end

  ## 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirm: 1, making: 2, preparing: 3, shipped: 4}

  def total_product_price
    total_product_price = 0
    self.order_details.each do |order_detail|
      sum = order_detail.price * order_detail.amount
      total_product_price += sum
    end
    return total_product_price
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { impossible: 0, waiting: 1, making: 2, finished: 3 }
  
  def total_item_price
    price*amount
  end
  
  
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page])

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.page(params[:page])
      render 'index'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.page(params[:page])
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image_id, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-light ">
  <div class="container">
    <div class="col-2">
      <%= link_to root_path do%>
        <%= image_tag 'logo', size: "100x100", class: "rounded-circle" %>
      <% end %>
    </div>
    <div class="col-10">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li>
              <%= link_to "商品一覧", admin_items_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
              <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
              <%= link_to "注文履歴一覧", admin_root_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
            <li>
              <%= button_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-dark' %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="text-right my-2">
        <input type="text" size="25" placeholder="Search">
      </div>
    </div>
  </div>
</nav>
</header>

app/views/layouts/_customer_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-light ">
  <div class="container">
    <div class="col-2">
      <%= link_to root_path do%>
        <%= image_tag 'logo', size: "100x100", class: "rounded-circle" %>
      <% end %>
    </div>
    <div class="col-10">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class="mx-auto">ようこそ、<%= current_customer.last_name %>さん！</div>
        <ul class="navbar-nav ml-auto">
            <li>
              <%= link_to "マイページ", my_page_customers_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
              <%= link_to "商品一覧", items_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
              <%= link_to "カート", cart_items_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-dark mx-2' %>
            </li>
        </ul>
      </div>
      <div class="text-right my-2">
        <input type="text" size="25" placeholder="Search">
      </div>
    </div>
  </div>
</nav>
</header>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight nagano_cake.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_guest_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-light ">
  <div class="container">
    <div class="col-2">
      <%= link_to root_path do%>
        <%= image_tag 'logo', size: "100x100", class: "rounded-circle"%>
      <% end %>
    </div>
    <div class="col-10">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <li>
              <%= link_to "About", about_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
              <%= link_to "商品一覧", items_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
              <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
            <li>
              <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-dark mx-2' %>
            </li>
        </ul>
      </div>
      <div class="text-right my-2">
        <input type="text" size="25" placeholder="Search">
      </div>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_customer == nil && current_admin == nil %>
      <%= render 'layouts/guest_header' %>
    <% elsif current_customer == nil && current_admin.present? %>
      <%= render 'layouts/admin_header' %>
    <% else current_customer == true && current_admin == nill %>
      <%= render 'layouts/customer_header' %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>